title: by Robin Dickson
email: robindickson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robin Dickson's projects and suchlike
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rbndickson.tech" # the base hostname & protocol for your site

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:slug/
  games:
    output: true
    permalink: /games/:slug/
