title: Robin Dickson
email: robindickson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robin Dickson's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rbndickson.github.io" # the base hostname & protocol for your site

index:
  en: /
  ja: /ja/

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:slug/

t:
  en:
    open_site: "Open Site"
    view_code: "View Code"
  ja:
    open_site: "サイトを開く"
    view_code: "コードを閲覧"
